# -*- coding: utf-8 -*-
"""web scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wrcdJuCcRWkNTemHqkaj2eukryyyq7nK
"""

import requests

!pip install mechanicalSoup

import mechanicalsoup
br = mechanicalsoup.StatefulBrowser()
br.open("http://www.rtovehicleinformation.com/")

form = br.select_form('#rto_adres_form1')
form.set("vehicle_shrt_name",number)

form.choose_submit(None)
response = br.submit_selected()

response.text

from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text,'html.parser')
tr = soup.find_all('tr')

tr[2].find_all('td')

[(tr[i].find_all('td')[0].get_text()+" : "+tr[i].find_all('td')[1].get_text())for i in range(0,5)]